# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master-optemi

jobs:
- job: Build
  timeoutInMinutes: 0

  variables:
    - group: che-theia
    - name: organization
      value: camino.azurecr.io
    - name: prefix
      value: optemi
    - name: tag
      value: next

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      dockerRegistryEndpoint: camino.azurecr.io
      containerRegistryType: Container Registry

  - script: |
      cd dockerfiles/theia-dev
      ./build.sh --build-args:$(github_token) --organization:$(organization) --tag:$(tag) --prefix:$(prefix)
    displayName: Building theia-dev
 
  - script: |
      export
      cd dockerfiles/theia
      ./build.sh --build-args:$(github_token),THEIA_VERSION=master --tag:$(tag) --prefix:$(prefix) --branch:master --git-ref:refs\\/heads\\/master --organization:$(organization)
    displayName: Building Theia

  - script: |
      docker push $(organization)/$(prefix)-theia-dev:$(tag)
      docker push $(organization)/$(prefix)-theia:$(tag)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: Pushing
